In [4]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
text = ["lonon paris london","paris paris london"]



In [31]:
cv = CountVectorizer()
cv_fit=cv.fit_transform(text)

text = ["london paris london","paris  paris london","paris london"]
# [keywords  name  director ]
# Distinace Between 2 Vectors

frequency = cv_fit.toarray()
print(frequency)


[[2 0 1]
 [1 1 2]
 [1 0 1]]


In [34]:
cosine_sim = cosine_similarity(frequency)
cosine_sim

array([[1.        , 0.73029674, 0.9486833 ],
       [0.73029674, 1.        , 0.8660254 ],
       [0.9486833 , 0.8660254 , 1.        ]])

In [36]:
get_like = 'paris london'
similar_movie_index = text.index(get_like)
similar_movies = list(enumerate(cosine_sim[similar_movie_index]))
similar_movies

[(0, 0.9486832980505137), (1, 0.8660254037844387), (2, 0.9999999999999998)]

In [37]:
sorted_similar_movies = sorted(similar_movies,key=lambda x:x[1],reverse = True)

In [38]:
sorted_similar_movies

[(2, 0.9999999999999998), (0, 0.9486832980505137), (1, 0.8660254037844387)]

In [52]:
for movie in sorted_similar_movies:
    if text[movie[0]] != get_like:
        print(text[movie[0]],'-Similarty:',round(movie[1]*100,3),'%')

london paris london -Similarty: 94.868 %
paris  paris london -Similarty: 86.603 %
